apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecommerce-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
        - name: ecommerce-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080

          env:
            - name: DB_HOST
              value: {{ .Values.config.dbHost | quote }}
            - name: DB_USER
              value: {{ .Values.config.dbUser | quote }}

          envFrom:
            - secretRef:
                name: ecommerce-secret
            - configMapRef:
                name: ecommerce-config

          resources:
            {{ toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5